export enum AuthTypes {
	LOGIN_REQUEST = "LOGIN_REQUEST",
	LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS",
	LOGIN_REQUEST_ERROR = "LOGIN_REQUEST_ERROR",

	LOGIN_REQUEST_STATE_RESET = "LOGIN_REQUEST_STATE_RESET"
}
