export enum MerchantsTypes {
	MERCHANTS_GET_REQUEST = "MERCHANTS_GET_REQUEST",
	MERCHANTS_GET_REQUEST_SUCCESS = "MERCHANTS_GET_REQUEST_SUCCESS",
	MERCHANTS_GET_REQUEST_UPDATE = "MERCHANTS_GET_REQUEST_UPDATE",
	MERCHANTS_GET_REQUEST_ERROR = "MERCHANTS_GET_REQUEST_ERROR",

	MERCHANTS_GET_SELECTED_REQUEST = "MERCHANTS_GET_SELECTED_REQUEST",
	MERCHANTS_GET_SELECTED_SUCCESS = "MERCHANTS_GET_SELECTED_SUCCESS",
	MERCHANTS_GET_SELECTED_ERROR = "MERCHANTS_GET_SELECTED_ERROR",

	MERCHANTS_DELETE_REQUEST = "MERCHANTS_DELETE_REQUEST",
	MERCHANTS_DELETE_REQUEST_SUCCESS = "MERCHANTS_DELETE_REQUEST_SUCCESS",
	MERCHANTS_DELETE_REQUEST_ERROR = "MERCHANTS_DELETE_REQUEST_ERROR",

	MERCHANTS_CREATE_REQUEST = "MERCHANTS_CREATE_REQUEST",
	MERCHANTS_CREATE_REQUEST_SUCCESS = "MERCHANTS_CREATE_REQUEST_SUCCESS",
	MERCHANTS_CREATE_REQUEST_ERROR = "MERCHANTS_CREATE_REQUEST_ERROR",

	MERCHANTS_UPDATE_REQUEST = "MERCHANTS_UPDATE_REQUEST",
	MERCHANTS_UPDATE_REQUEST_SUCCESS = "MERCHANTS_UPDATE_REQUEST_SUCCESS",
	MERCHANTS_UPDATE_REQUEST_ERROR = "MERCHANTS_UPDATE_REQUEST_ERROR",
	MERCHANTS_UPDATE_STATE_RESET = "MERCHANTS_UPDATE_STATE_RESET",

	MERCHANTS_DRAWER_TOGGLE = "MERCHANTS_DRAWER_TOGGLE"
}
